//! Bee-derived conformance test vectors.
//!
//! The JSON files under `conformance/vectors/` are generated by the Go
//! program in `conformance/vectorgen/`, which calls the canonical bee
//! implementation (the sibling `bee` checkout) for every derived value:
//! CAC/BMT addresses, SOC signatures + addresses, feed identifiers, full
//! feed-update chunks, postage stamp digests + signatures, dispersed
//! replica addresses, and the erasure-code parity tables.
//!
//! The tests in `tests/vectors.rs` assert that ant's implementations are
//! bit-exact against those vectors. Regenerate the vectors with:
//!
//! ```sh
//! cd conformance/vectorgen && go run . -out ../vectors
//! ```

pub mod memnode;

pub use memnode::{
    mem_node_public_key_hex, spawn_mem_gateway, MemChunkStore, MemGateway, MemGatewayConfig,
    MEM_NODE_SECRET,
};

use serde::de::DeserializeOwned;
use serde::Deserialize;
use std::path::PathBuf;

/// Directory holding the generated vector JSON files.
#[must_use]
pub fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("conformance")
        .join("vectors")
}

/// Load and deserialize one vector file by name (e.g. `"soc.json"`).
///
/// # Panics
///
/// Panics if the file is missing or malformed — vectors are checked in,
/// so either is a repo defect, not a runtime condition.
#[must_use]
pub fn load<T: DeserializeOwned>(name: &str) -> T {
    let path = vectors_dir().join(name);
    let blob =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read vector file {}: {e}", path.display()));
    serde_json::from_slice(&blob)
        .unwrap_or_else(|e| panic!("parse vector file {}: {e}", path.display()))
}

/// Decode a hex vector field, panicking with the field name on error.
#[must_use]
pub fn unhex(field: &str, s: &str) -> Vec<u8> {
    hex::decode(s).unwrap_or_else(|e| panic!("bad hex in vector field {field}: {e}"))
}

/// Decode a fixed-size hex vector field.
#[must_use]
pub fn unhex_arr<const N: usize>(field: &str, s: &str) -> [u8; N] {
    let v = unhex(field, s);
    let len = v.len();
    v.try_into()
        .unwrap_or_else(|_| panic!("vector field {field}: expected {N} bytes, got {len}"))
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacVectors {
    pub cases: Vec<CacCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CacCase {
    pub name: String,
    pub payload_hex: String,
    pub span_hex: String,
    pub address_hex: String,
    pub chunk_data_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SocVectors {
    pub cases: Vec<SocCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SocCase {
    pub name: String,
    pub secret_hex: String,
    pub owner_hex: String,
    pub id_hex: String,
    pub payload_hex: String,
    pub cac_address_hex: String,
    pub digest_hex: String,
    pub signature_hex: String,
    pub soc_address_hex: String,
    pub chunk_data_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedSequenceVectors {
    pub cases: Vec<FeedIdCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedIdCase {
    pub topic_hex: String,
    pub index: String,
    pub id_hex: String,
    pub owner_hex: String,
    pub soc_address_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedEpochVectors {
    pub cases: Vec<EpochIdCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EpochIdCase {
    pub start: String,
    pub level: u8,
    pub index_bytes_hex: String,
    pub topic_hex: String,
    pub id_hex: String,
    pub owner_hex: String,
    pub soc_address_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedUpdateVectors {
    pub cases: Vec<FeedUpdateCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedUpdateCase {
    pub kind: String,
    pub secret_hex: String,
    pub owner_hex: String,
    pub topic_hex: String,
    pub index: String,
    pub payload_hex: String,
    pub id_hex: String,
    pub signature_hex: String,
    pub soc_address_hex: String,
    pub chunk_data_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StampVectors {
    pub cases: Vec<StampCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StampCase {
    pub name: String,
    pub secret_hex: String,
    pub owner_hex: String,
    pub chunk_addr_hex: String,
    pub batch_id_hex: String,
    pub index_hex: String,
    pub timestamp_hex: String,
    pub digest_hex: String,
    pub signature_hex: String,
    pub stamp_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReplicaVectors {
    pub base_address_hex: String,
    pub replicas_owner_hex: String,
    pub replica_counts: Vec<u32>,
    pub cases: Vec<ReplicaCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReplicaCase {
    pub entropy: u8,
    pub id_hex: String,
    pub soc_address_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RsFileVectors {
    pub cases: Vec<RsFileCase>,
}

/// One file encoded by bee's real pipeline (`builder.NewPipelineBuilder`)
/// at a `swarm-redundancy-level`. `chunks` holds **every** chunk the
/// pipeline emitted — data, intermediate and parity — and
/// `root_replicas` the dispersed replica SOC wires `replicas.NewPutter`
/// would upload for the root. The file payload is `det("rs/<name>",
/// file_size)` (see `conformance/vectorgen/main.go`).
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RsFileCase {
    pub name: String,
    pub level: u8,
    pub file_size: usize,
    pub root_hex: String,
    pub chunks: Vec<RsChunkEntry>,
    pub root_replicas: Vec<RsChunkEntry>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RsChunkEntry {
    pub address_hex: String,
    pub data_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RedundancyVectors {
    pub levels: Vec<RedundancyLevel>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RedundancyLevel {
    pub level: u8,
    pub name: String,
    pub replica_count: u32,
    pub max_shards: u32,
    pub max_enc_shards: u32,
    pub parities: Vec<u32>,
    pub enc_parities: Vec<u32>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EncryptionVectors {
    pub chunk_cases: Vec<EncChunkCase>,
    pub tree_cases: Vec<EncTreeCase>,
}

/// One chunk encrypted with bee's `pkg/encryption` primitives under an
/// **injected** key (zero ciphertext padding) — byte-exact targets for
/// ant's `encrypt_chunk_unpadded` / `decrypt_chunk`.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EncChunkCase {
    pub name: String,
    pub key_hex: String,
    pub payload_hex: String,
    pub plain_span_hex: String,
    pub enc_span_hex: String,
    pub enc_data_hex: String,
    pub stored_wire_hex: String,
    pub address_hex: String,
}

/// One whole encrypted tree frozen from bee's *real* pipeline
/// (`builder.NewPipelineBuilder` with `encrypt = true`; random keys,
/// fixed once generated). The payload is `det("enc/<name>", file_size)`.
/// Ant's `join_encrypted` must reproduce it from `root_ref_hex`.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EncTreeCase {
    pub name: String,
    pub level: u8,
    pub file_size: usize,
    pub root_ref_hex: String,
    pub chunks: Vec<RsChunkEntry>,
    pub root_replicas: Vec<RsChunkEntry>,
}

// --- ACT (access control) vectors -------------------------------------------

/// `act.json`: bee's `pkg/accesscontrol` primitives with injected keys
/// (KDF / wrap / reference encryption / kvs manifest / history
/// manifests + lookup table) plus two frozen full-controller flows.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActVectors {
    pub publisher_secret_hex: String,
    pub publisher_pub_hex: String,
    pub kdf_cases: Vec<ActKdfCase>,
    pub ref_cases: Vec<ActRefCase>,
    pub kvs_cases: Vec<ActKvsCase>,
    pub history_cases: Vec<ActHistoryCase>,
    pub upload_flow: ActUploadFlow,
    pub grantee_flow: ActGranteeFlow,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActKdfCase {
    pub name: String,
    pub secret_hex: String,
    pub counterparty_pub_hex: String,
    pub lookup_key_hex: String,
    pub akdk_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActRefCase {
    pub name: String,
    pub ref_hex: String,
    pub access_key_hex: String,
    pub encrypted_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActKvsCase {
    pub name: String,
    pub rows: Vec<ActKvsRow>,
    pub manifest_json: String,
    pub root_hex: String,
    pub chunks: Vec<RsChunkEntry>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActKvsRow {
    pub key_hex: String,
    pub value_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActHistoryCase {
    pub name: String,
    pub steps: Vec<ActHistoryStep>,
    pub lookups: Vec<ActLookupCase>,
    pub chunks: Vec<RsChunkEntry>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActHistoryStep {
    pub timestamp: i64,
    pub act_ref_hex: String,
    #[serde(default)]
    pub metadata: std::collections::BTreeMap<String, String>,
    pub root_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActLookupCase {
    pub timestamp: i64,
    #[serde(default)]
    pub act_ref_hex: String,
    #[serde(default)]
    pub error: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActUploadFlow {
    pub publisher_secret_hex: String,
    pub content_ref_hex: String,
    pub history_ref_hex: String,
    pub encrypted_ref_hex: String,
    pub chunks: Vec<RsChunkEntry>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActGranteeFlow {
    pub publisher_secret_hex: String,
    pub grantee_secrets_hex: Vec<String>,
    pub grantee_pubs_hex: Vec<String>,
    pub egrantee_ref_hex: String,
    pub history_ref_hex: String,
    pub content_ref_hex: String,
    pub encrypted_ref_hex: String,
    pub chunks: Vec<RsChunkEntry>,
}
